name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    steps:
    - name: Create target dir
      run: mkdir target
    - uses: actions/checkout@v4
    - name: make
      run: make
